# DEP Exp 2

In [1]:
import pandas as pd
import numpy as np
import statistics as stc

#Q1
MSFT = [150, 175, 200, 215, 200]
FB = [120, 125, 140, 145, 160]
msftarr = np.array(MSFT)
fbarr = np.array(FB)

#Q2
Stock = np.concatenate([msftarr, fbarr])
print(msftarr, fbarr, "Concatenate:", Stock, sep="\n")

#Q3
print("Matrix")
mat = np.matrix([msftarr, fbarr])
print(mat)

#Q4
M3d = np.zeros((3,3,3))
M3d[::2, ::2, ::2] = 1
M3d[::2, 1::2, 1::2] = 1
M3d[1::2, ::2, ::2] = 1
M3d[1,1,1] = 1
print(M3d)

#Q5
gender = ['Female', 'male', 'Male', 'M', 'F', 'F']
factor = set(gender)
print(factor, "\n")

#Q6
empId = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
empName = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
age = [19, 21, 22, 24, 34, 51, 28, 39, 30, 35]
sal = [10000, 12000, 14000, 17500, 20000, 45000, 30000, 19500, 30000, 32000]
DF = pd.DataFrame([empId, empName, age, sal])
print(DF, "\n")
print("Average salary is:\t", np.mean(sal))
print("Std. Deviation of salary is:\t", stc.stdev(sal), "\n")
gdr = gender
for i in gdr:
    level = int(0)
    for g in range(0,len(gdr)):
        if i == gdr[g]:
            level+=1
    print("Level of", i, "=", level)

[150 175 200 215 200]
[120 125 140 145 160]
Concatenate:
[150 175 200 215 200 120 125 140 145 160]
Matrix
[[150 175 200 215 200]
 [120 125 140 145 160]]
[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]
{'F', 'male', 'M', 'Female', 'Male'} 

       0      1      2      3      4      5      6      7      8      9
0    101    102    103    104    105    106    107    108    109    110
1      A      B      C      D      E      F      G      H      I      J
2     19     21     22     24     34     51     28     39     30     35
3  10000  12000  14000  17500  20000  45000  30000  19500  30000  32000 

Average salary is:	 23000.0
Std. Deviation of salary is:	 10982.309006357047 

Level of Female = 1
Level of male = 1
Level of Male = 1
Level of M = 1
Level of F = 2
Level of F = 2


In [23]:
# x -> matrix no, y -> row no, z -> col no

[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]
